/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.75).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.DocumentListRequest;
import io.swagger.model.DocumentRetrievalResponse;
import io.swagger.model.ErrorResponse;
import java.util.UUID;
import io.swagger.model.XRequestorType;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2025-11-24T22:19:46.681626062Z[GMT]")
@Validated
public interface DocumentsEnquiryApi {

    @Operation(summary = "This endpoint will return a document list according to the given parameters in the request body.", description = "", tags={ "Document List Retrieval" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful Retrieval", content = @Content(mediaType = "application/json", schema = @Schema(implementation = DocumentRetrievalResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized access to an endpoint", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "403", description = "Forbidden", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "404", description = "Not Found", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "503", description = "Service Unavailable", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/documents-enquiry",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<DocumentRetrievalResponse> documentsEnquiryPost(@Parameter(in = ParameterIn.HEADER, description = "Api version" ,required=true,schema=@Schema()) @RequestHeader(value="X-version", required=true) Integer xVersion
, @Parameter(in = ParameterIn.HEADER, description = "Correlation ID for request tracing" ,required=true,schema=@Schema()) @RequestHeader(value="X-correlation-id", required=true) String xCorrelationId
, @Parameter(in = ParameterIn.HEADER, description = "Id of the requestor" ,required=true,schema=@Schema()) @RequestHeader(value="X-requestor-id", required=true) UUID xRequestorId
, @Parameter(in = ParameterIn.HEADER, description = "Type of the requestor" ,required=true,schema=@Schema()) @RequestHeader(value="X-requestor-type", required=true) XRequestorType xRequestorType
, @Parameter(in = ParameterIn.DEFAULT, description = "", schema=@Schema()) @Valid @RequestBody DocumentListRequest body
);

}

