/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.75).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.DocumentDetailsNode;
import io.swagger.model.ErrorResponse;
import io.swagger.model.InlineResponse200;
import io.swagger.model.Metadata;
import org.springframework.core.io.Resource;
import java.util.UUID;
import io.swagger.model.XRequestorType;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2025-11-24T22:19:46.681626062Z[GMT]")
@Validated
public interface DocumentsApi {

    @Operation(summary = "Upload a document", description = "Uploads a document for storage.    The files currently are not scanned for viruses on the server end. It'll be part of a future implementation. Currently it'll be the responibility of the client.      For text based files, if Byte Order Mark (BOM) is present, it will be preserved. It is the responsibility of the client to correclty handle the BOM at the time of retrieval. ", tags={ "Document Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InlineResponse200.class))),
        
        @ApiResponse(responseCode = "400", description = "Bad Request", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized access to an endpoint", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "404", description = "Not Found", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "409", description = "Cannot be processed. Antivirus scan failed.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "Internal Server Error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "503", description = "Service Unavailable", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/documents",
        produces = { "application/json" }, 
        consumes = { "multipart/form-data" }, 
        method = RequestMethod.POST)
    ResponseEntity<InlineResponse200> addDocument(@Parameter(in = ParameterIn.HEADER, description = "Api version" ,required=true,schema=@Schema()) @RequestHeader(value="X-version", required=true) Integer xVersion
, @Parameter(in = ParameterIn.HEADER, description = "Correlation ID for request tracing" ,required=true,schema=@Schema()) @RequestHeader(value="X-correlation-id", required=true) String xCorrelationId
, @Parameter(in = ParameterIn.HEADER, description = "Id of the requestor" ,required=true,schema=@Schema()) @RequestHeader(value="X-requestor-id", required=true) UUID xRequestorId
, @Parameter(in = ParameterIn.HEADER, description = "Type of the requestor" ,required=true,schema=@Schema()) @RequestHeader(value="X-requestor-type", required=true) XRequestorType xRequestorType
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true,schema=@Schema()) @RequestPart(value="documentType", required=true)  String documentType
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true,schema=@Schema()) @RequestPart(value="createdBy", required=true)  UUID createdBy
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true,schema=@Schema()) @RequestPart(value="templateId", required=true)  UUID templateId
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true,schema=@Schema()) @RequestPart(value="referenceKey", required=true)  String referenceKey
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true,schema=@Schema()) @RequestPart(value="referenceKeyType", required=true)  String referenceKeyType
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true,schema=@Schema()) @RequestPart(value="accountKey", required=true)  UUID accountKey
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true,schema=@Schema()) @RequestPart(value="customerKey", required=true)  UUID customerKey
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true,schema=@Schema()) @RequestPart(value="category", required=true)  String category
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true,schema=@Schema()) @RequestPart(value="fileName", required=true)  String fileName
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true,schema=@Schema()) @RequestPart(value="activeStartDate", required=true)  Long activeStartDate
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true,schema=@Schema()) @RequestPart(value="activeEndDate", required=true)  Long activeEndDate
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true,schema=@Schema()) @RequestPart(value="threadId", required=true)  UUID threadId
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true,schema=@Schema()) @RequestPart(value="correlationId", required=true)  UUID correlationId
, @Parameter(description = "") @Valid @RequestPart(value="content", required=true) MultipartFile content
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true,schema=@Schema()) @RequestPart(value="metadata", required=true)  Metadata metadata
);


    @Operation(summary = "Deletes the document identified by \"documentId\" ", description = "", tags={ "Document Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "204", description = "Successful operation"),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized access to an endpoint", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "403", description = "Forbidden", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "404", description = "Not Found", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "503", description = "Service Unavailable", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/documents/{documentId}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> documentDelete(@Parameter(in = ParameterIn.HEADER, description = "Api version" ,required=true,schema=@Schema()) @RequestHeader(value="X-version", required=true) Integer xVersion
, @Parameter(in = ParameterIn.HEADER, description = "Correlation ID for request tracing" ,required=true,schema=@Schema()) @RequestHeader(value="X-correlation-id", required=true) String xCorrelationId
, @Parameter(in = ParameterIn.HEADER, description = "Id of the requestor" ,required=true,schema=@Schema()) @RequestHeader(value="X-requestor-id", required=true) UUID xRequestorId
, @Parameter(in = ParameterIn.HEADER, description = "Type of the requestor" ,required=true,schema=@Schema()) @RequestHeader(value="X-requestorType", required=true) XRequestorType xRequestorType
, @Size(max=500) @Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("documentId") String documentId
);


    @Operation(summary = "Downloads the document identified by \"documentId\" ", description = "", tags={ "Document Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Resource.class))),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized access to an endpoint", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "403", description = "Forbidden", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "404", description = "Not Found", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "503", description = "Service Unavailable", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/documents/{documentId}",
        produces = { "application/octet-stream", "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Resource> documentDownload(@Parameter(in = ParameterIn.HEADER, description = "Api version" ,required=true,schema=@Schema()) @RequestHeader(value="X-version", required=true) Integer xVersion
, @Parameter(in = ParameterIn.HEADER, description = "Correlation ID for request tracing" ,required=true,schema=@Schema()) @RequestHeader(value="X-correlation-id", required=true) String xCorrelationId
, @Size(max=500) @Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("documentId") String documentId
, @Parameter(in = ParameterIn.HEADER, description = "Type of the requestor" ,required=true,schema=@Schema()) @RequestHeader(value="X-requestor-type", required=true) XRequestorType xRequestorType
, @Parameter(in = ParameterIn.HEADER, description = "Id of the requestor" ,required=true,schema=@Schema()) @RequestHeader(value="X-requestor-id", required=true) UUID xRequestorId
);


    @Operation(summary = "Retreives the metadata for the document identified by documentId", description = "", tags={ "Document Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", schema = @Schema(implementation = DocumentDetailsNode.class))),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized access to endpoint", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "403", description = "Forbidden", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "404", description = "Not Found", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "503", description = "Service Unavailable", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/documents/{documentId}/metadata",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<DocumentDetailsNode> documentMetadata(@Parameter(in = ParameterIn.HEADER, description = "Api version" ,required=true,schema=@Schema()) @RequestHeader(value="X-version", required=true) Integer xVersion
, @Parameter(in = ParameterIn.HEADER, description = "Correlation ID for request tracing" ,required=true,schema=@Schema()) @RequestHeader(value="X-correlation-id", required=true) String xCorrelationId
, @Size(max=500) @Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("documentId") String documentId
, @Parameter(in = ParameterIn.HEADER, description = "Type of the requestor" ,required=true,schema=@Schema()) @RequestHeader(value="X-requestor-type", required=true) XRequestorType xRequestorType
, @Parameter(in = ParameterIn.HEADER, description = "Id of the requestor" ,required=true,schema=@Schema()) @RequestHeader(value="X-requestor-id", required=true) UUID xRequestorId
, @Parameter(in = ParameterIn.QUERY, description = "Indicates if ECMS document download url to be included in response" ,schema=@Schema( defaultValue="false")) @Valid @RequestParam(value = "includeDownloadUrl", required = false, defaultValue="false") Boolean includeDownloadUrl
);

}

