CREATE TABLE "master_template_definition" (
  "master_template_id" UUID,
  "template_version " int,
  "legacy_template_id" varchar,
  "legacy_template_name" varchar,
  "display_name" varchar,
  "template_name" varchar,
  "template_description " varchar,
  "template_category " varchar,
  "line_of_business" varchar,
  "template_type" varchar,
  "language_code" varchar,
  "owning_dept" varchar,
  "notification_needed" bit BOOLEAN DEFAULT false,
  "is_active" bit BOOLEAN DEFAULT false,
  "is_regulatory" bit BOOLEAN DEFAULT false,
  "is_message_center_doc" bit BOOLEAN DEFAULT false,
  "is_shared_document" bit BOOLEAN DEFAULT false,
  "sharing_scope" varchar,
  "data_extraction_config" jsonb,
  "access_control" jsonb,
  "channels" jsonb,
  "required_fields" jsonb,
  "template_config" jsonb,
  "start_date" long,
  "end_date" long,
  "created_by" varchar,
  "created_timestamp" TIMESTAMPTZ DEFAULT NOW(),
  "update_by" varchar,
  "updated_timestamp" TIMESTAMPTZ DEFAULT NOW(),
  "archive_indicator" bit,
  "archive_timestamp" timestamp,
  "version_number" bigint,
  "record_status" bigint,
  -- Constraints
  PRIMARY KEY ("master_template_id", "template_version "),
  UNIQUE ("template_version", "template_type", "line_of_business")
);

CREATE TABLE "storage_index" (
  "storage_index_id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "master_template_id" UUID NOT NULL REFERENCES master_template_definition(master_template_id),
  "template_version " int NOT NULL REFERENCES master_template_definition(template_version),
  "template_type" varchar,
  "reference_key" varchar,
  "reference_key_type" varchar,
  "is_shared" bit,
  "account_key" UUID,
  "customer_key" UUID,
  "storage_vendor" varchar,
  "storage_document_key" UUID,
  "generation_vendor" varchar,
  "file_name" varchar,
  "doc_creation_date" long,
  "is_accessible" int,
  "doc_metadata" jsonb,
  "created_by" varchar,
  "created_timestamp" TIMESTAMPTZ DEFAULT NOW(),
  "update_by" varchar,
  "updated_timestamp" TIMESTAMPTZ DEFAULT NOW(),
  "archive_indicator" bit,
  "archive_timestamp" timestamp,
  "version_number" bigint,
  "record_status" bigint,
  PRIMARY KEY ("storage_index_id")
);

CREATE TABLE "template_vendor_mapping" (
  "template_vendor_id" UUID,
  "master_template_id" UUID NOT NULL REFERENCES master_template_definition(master_template_id),
  "template_version " int NOT NULL REFERENCES master_template_definition(template_version),
  "vendor" enum,
  "vendor_template_key" varchar,
  "vendor_template_name" varchar,
  "reference_key_type" varchar,
  "consumer_id" UUID,
  "template_content" blob,
  "start_date" long(Epoch),
  "end_date" long(Epoch),
  "vendor_mapping_version" int,
  "schema_info" jsonb,
  "template_fields" jsonb,
  "vendor_config" jsonb,
  "api_config" jsonb,
  "is_active" bit,
  "is_primary" bit,
  "created_by" varchar,
  "created_timestamp" TIMESTAMPTZ DEFAULT NOW(),
  "updated_by" varchar,
  "updated_timestamp" TIMESTAMPTZ DEFAULT NOW(),
  "archive_indicator" bit,
  "archive_timestamp" timestamp,
  "record_status" bigint,
  "template_status" enum ,
  PRIMARY KEY ("template_vendor_id"),
  CHECK (template_status IN ('DRAFT', 'APPROVED', 'REJECTED', 'PENDING', 'ARCHIVED'))
);


