-- H2 Database Schema for Document Hub POC
-- Compatible with H2 in-memory database

CREATE TABLE IF NOT EXISTS master_template_definition
(
    master_template_id uuid NOT NULL,
    template_version integer NOT NULL,
    legacy_template_id varchar,
    template_name varchar NOT NULL,
    template_description varchar,
    line_of_business varchar,
    template_category varchar,
    template_type_old varchar,
    language_code varchar,
    owning_dept varchar,
    notification_needed boolean NOT NULL DEFAULT false,
    regulatory_flag boolean NOT NULL DEFAULT false,
    message_center_doc_flag boolean NOT NULL DEFAULT false,
    document_channel_old varchar,
    template_variables varchar,
    start_date bigint,
    end_date bigint,
    created_by varchar NOT NULL,
    created_timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by varchar,
    updated_timestamp timestamp,
    archive_indicator boolean NOT NULL DEFAULT false,
    archive_timestamp timestamp,
    version_number bigint NOT NULL DEFAULT 0,
    record_status varchar NOT NULL DEFAULT '1',
    legacy_template_name varchar,
    display_name varchar,
    template_type varchar,
    active_flag boolean,
    shared_document_flag boolean,
    data_extraction_config varchar,
    access_control varchar,
    required_fields varchar,
    template_config varchar,
    sharing_scope varchar,
    CONSTRAINT master_template_definition_pkey PRIMARY KEY (master_template_id, template_version)
);

CREATE TABLE IF NOT EXISTS storage_index
(
    storage_index_id uuid NOT NULL,
    master_template_id uuid NOT NULL,
    storage_vendor varchar,
    reference_key varchar,
    reference_key_type varchar,
    account_key uuid,
    customer_key uuid,
    storage_document_key uuid,
    file_name varchar,
    doc_creation_date bigint,
    accessible_flag boolean NOT NULL DEFAULT true,
    doc_metadata varchar,
    created_by varchar NOT NULL,
    created_timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by varchar,
    updated_timestamp timestamp,
    archive_indicator boolean NOT NULL DEFAULT false,
    archive_timestamp timestamp,
    version_number bigint NOT NULL DEFAULT 0,
    record_status varchar NOT NULL DEFAULT '1',
    template_version integer,
    template_type varchar,
    shared_flag boolean NOT NULL DEFAULT false,
    generation_vendor_id uuid,
    CONSTRAINT storage_index_pkey PRIMARY KEY (storage_index_id)
);

CREATE TABLE IF NOT EXISTS template_vendor_mapping
(
    template_vendor_id uuid NOT NULL,
    master_template_id uuid NOT NULL,
    vendor varchar NOT NULL,
    vendor_template_key varchar,
    reference_key_type varchar,
    consumer_id uuid,
    template_content blob,
    start_date bigint,
    end_date bigint,
    vendor_mapping_version integer NOT NULL DEFAULT 1,
    primary_flag boolean NOT NULL DEFAULT false,
    schema_info varchar,
    active_flag boolean NOT NULL DEFAULT true,
    created_by varchar NOT NULL,
    created_timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by varchar,
    updated_timestamp timestamp,
    archive_indicator boolean NOT NULL DEFAULT false,
    archive_timestamp timestamp,
    record_status varchar NOT NULL DEFAULT '1',
    version_number bigint,
    template_version integer,
    vendor_template_name varchar,
    template_fields varchar,
    vendor_config varchar,
    api_config varchar,
    template_status varchar,
    CONSTRAINT template_vendor_mapping_pkey PRIMARY KEY (template_vendor_id)
);
